### PR TITLE
Fix SetRequestCallbacks/SetResponseCallbacks

### LINKED ISSUE #241: SetRequestCallbacks not working
# Expected Behavior
When using `SetRequestCallbacks`, i expected the `callbacks` should be set to the `requestCallbacks` in client. 

```
client.SetRequestCallbacks(func(req *http.Request) {
    fmt.Println("client callback")
})
```

# Current Behavior
The `requestCallbacks` in client is still empty.

I think the reason the `requestCallbacks` not being copy is due to the copy function. 
https://github.com/hashicorp/vault-client-go/blob/fd98162630955fc3bcf963e725733903102a8787/request_modifiers.go#L173
```
// SetRequestCallbacks sets callbacks which will be invoked before each request.
func (c *Client) SetRequestCallbacks(callbacks ...RequestCallback) error {
	c.clientRequestModifiersLock.Lock()
	copy(c.clientRequestModifiers.requestCallbacks, callbacks)
	c.clientRequestModifiersLock.Unlock()

	return nil
}
```
As mentioned in the [Copy](https://pkg.go.dev/builtin#copy), 

> Copy returns the number of elements copied, which will be the minimum of len(src) and len(dst).

So, when the client is initialized as no `requestCallbacks`, the copy function will always copy nothing to the `requestCallbacks`.

To solve the bug, I think you can change to use `append` to fix it.
```
c.clientRequestModifiers.requestCallbacks = append(c.clientRequestModifiers.requestCallbacks, callbacks...)
```

# Failure Information
vault-client-go: 0.4.1

Please include the version of Vault binary and the version of `vault-client-go` you're using.

## Steps to Reproduce

Please provide detailed steps for reproducing the issue.
```
client, _ := vault.New()

client.SetRequestCallbacks(func(req *http.Request) {
    fmt.Println("client callback")
})
```

# Additional Information
I think the `SetResponseCallbacks` having same issue.
https://github.com/hashicorp/vault-client-go/blob/fd98162630955fc3bcf963e725733903102a8787/request_modifiers.go#L190

### PR DESCRIPTION
**Pull request by averche**
## Description

`SetRequestCallbacks/SetResponseCallbacks` was incorrectly using the built-in `copy` function. As @joseph-reslv pointed out in https://github.com/hashicorp/vault-client-go/issues/241#issue-1941186005:

> Copy returns the number of elements copied, which will be the minimum of len(src) and len(dst).

Fixing the instances where we call `copy` incorrectly to fix the two functions.

Resolves #241 

## How has this been tested?

Unfortunately we don't have a robust testing framework, so I won't be able to properly test these use-cases. However, I've tested it in https://github.com/averche/vault-test/pull/4 and I see the new code working as expected.

### CODE REVIEW

File: client.go [hunk 1]
```diff
@@ -204,8 +204,8 @@ func (c *Client) cloneClientRequestModifiers() requestModifiers {
 
 	var clone requestModifiers
 
-	copy(clone.requestCallbacks, c.clientRequestModifiers.requestCallbacks)
-	copy(clone.responseCallbacks, c.clientRequestModifiers.responseCallbacks)
+	clone.requestCallbacks = append([]RequestCallback{}, c.clientRequestModifiers.requestCallbacks...)
+	clone.responseCallbacks = append([]ResponseCallback{}, c.clientRequestModifiers.responseCallbacks...)
```
Comment (dhuckins) [inline client.go:208]: don't think ive seen this pattern in golang before, can we use something like https://pkg.go.dev/slices#Clone instead?

Comment (averche) [reply client.go:208]: Nice, this actually [implements](https://cs.opensource.google/go/go/+/refs/tags/go1.21.3:src/slices/slices.go;l=336-344) what I was trying to do! I definitely like this better, thanks!

Comment (averche) [reply client.go]: https://github.com/hashicorp/vault-client-go/pull/242/commits/c439fb70447fb743fb3cef541d648bd66bf69c39

**Review by dhuckins — APPROVED** [review]
